apiVersion: v1
kind: Secret
metadata:
  name: gitlabregistrykey
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

---

apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
type: Opaque
stringData:
  DATABASE_URL: "{{ .Values.dotenv.DATABASE_URL }}"

---
  
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
data:
  DJANGO_ADMIN_URL: "{{ .Values.dotenv.DJANGO_ADMIN_URL }}"
  DJANGO_DEBUG: "{{ .Values.dotenv.DJANGO_DEBUG }}"
  DJANGO_SECRET_KEY: "{{ .Values.dotenv.DJANGO_SECRET_KEY }}"
  DJANGO_SETTINGS_MODULE: "{{ .Values.dotenv.DJANGO_SETTINGS_MODULE }}"
  REDIS_URL: "{{ .Values.dotenv.REDIS_URL }}"
  SITE_DOMAIN: "{{ .Values.dotenv.SITE_DOMAIN }}"
  SITE_SCHEME: "{{ .Values.dotenv.SITE_SCHEME }}"
