apiVersion: v1
kind: Secret
metadata:
  name: gitlabregistrykey
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

---

apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
type: Opaque
stringData:
  DUMMY: "{{ .Values.dotenv.DUMMY}}"

---
  
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
data:
  DUMMY: "{{ .Values.dotenv.DUMMY}}"
